In [5]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from scipy import optimize
from ipywidgets import *
from IPython.display import SVG
from sklearn import datasets              

AND=pd.DataFrame({'x1':(0,0,1,1),'x2':(0,1,0,1),'y':(0,0,0,1)})


In [6]:
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [7]:
w=np.random.randn(3)*1e-4
w

array([-5.64043665e-05,  1.81491554e-05,  3.86881657e-05])

In [12]:
inputs =AND[['x1','x2']]
target=AND['y']

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [11]:
g= lambda inputs ,weights:np.where(np.dot(inputs,weights)>0,1,0)

In [13]:
def train(inputs,targets,weights,eta,n_iterations):
    inputs=np.c_[inputs,-np.ones((len(inputs),1))]
    for n in range(n_iterations):
        activations=g(inputs,weights)
        weights-=eta*(np.dot(np.transpose(inputs),activations-targets))
    return (weights)

In [32]:
w=train(inputs,target,w,10,2)

In [34]:
g(np.c_[inputs,-np.ones((len(inputs),1))],w)

array([0, 0, 0, 1])

In [35]:
np.c_[inputs,-np.ones((len(inputs),1))]

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])